feat: add creators cards&button
IT-FAMCS/legacy pull request #14
Opened 2024-04-17 14:59 UTC by sans-et

2024-04-18 20:16 UTC, PblCbGomel requested changes

2024-04-18 20:16 UTC, PblCbGomel commented on front-app/src/App.tsx
> +        <img src={racoon} alt="Raccoon logo" className="RaccconLogo"></img>
Только сейчас заметил: замеги на `<img src={racoon} alt="Raccoon logo" className="RaccconLogo"/>` картинка делается без закрывающего тега

2024-04-18 20:16 UTC, PblCbGomel commented on front-app/src/App.tsx
>        </body>
довай `body` заменим на `main`, семантически правильно

2024-04-18 20:16 UTC, PblCbGomel commented on front-app/src/App.tsx
>        </body>
в стилях тоже поменять над будет

2024-04-18 20:16 UTC, PblCbGomel commented on front-app/src/constants/creators-info.ts
> +    git: "PBLCbGomel",
Ну эт.. PblCbGomel (не все буквы большые вначале)

2024-04-18 20:17 UTC, sans-et commented on front-app/src/constants/creators-info.ts
> +    git: "PBLCbGomel",
Это такой шрифт, он делает все большие буквы, нужно потом стилизовать)

2024-04-19 18:17 UTC, PblCbGomel approved these changes

2024-04-19 18:17 UTC, merged